### PR TITLE
feat: add Search UI

### PR DESCRIPTION
**Pull request by icaraps**
https://user-images.githubusercontent.com/6012307/128221398-b19c7285-2356-4f20-99e7-305f2bda665b.mov

### CODE REVIEW

**Comment by bdenham** [comment]
Hey Stephan, thanks for the work on the modal and autocomplete. I'll merge this branch with the core search_ui branch because a lot has changed since this branch was created from main on June 21. 

This is a good start. I'll look closely at the code and add dividers and additional indexes searched as needed.

**Comment by bdenham** [comment]
I commend your effort, but ultimately this isn't useful. I wish you would have worked within the SearchPage and SearchWidget components we were almost finished with instead of starting from scratch and essentially ignoring all the work that was already there and in place.

**Comment by icaraps** [comment]
Sorry I didn't find another quick solution to get the UI in a ready state for the go live. The work with the Algolia components is not lost, if times allow we can find a solution to get them working with Spectrum CSS. Please keep in mind, non Spectrum UI is not allowed.  
Meanwhile, I'll move on, merge, release and deploy as we don't have much time left.

**Comment by bdenham** [comment]
Ok, well, I guess I'll stop my implementation for what I'm doing with Algolia's autocomplete and react-modal.

**Comment by bdenham** [comment]
> Sorry I didn't find another quick solution to get the UI in a ready state for the go-live. The work with the Algolia components is not lost, if time allows we can find a solution to get them working with Spectrum CSS.

@icaraps, I just want to state for the record, that Tim and I already had a solution to styling the search UI components with Spectrum CSS. I don't know where you got the idea that we were experimenting with that. But Tim had already successfully styled the existing components using the connect API that Tim had already demonstrated in the code and could have easily told you about had you simply ask us both at any time. Here's one such instance that has been in the code for some time, long prior to your decision to redo the UI:

```const HitsPerPageSpectrum = ({ items, refine }) => (
  <Picker
    isQuiet
    items={items.map((item, i) => ({
      title: item.label,
      selected: i === 0
    }))}
    onChange={(index) => {
      refine(items[index].value);
    }}
  />
);

const CustomHitsPerPage = connectHitsPerPage(HitsPerPageSpectrum);
``` 

 @icaraps As far as your statement about Spectrum CSS:
 
 > Please keep in mind, non Spectrum UI is not allowed.

We all understood that. And were not concerned about this to start testing. Adding Spectrum CSS changes can be done and will be done during testing. So again, it was not an adequate reason to subvert all the existing UI components and framework. And again, if you were not sure how to do something — especially something as easy as styling — then you could have quickly and easily asked Tim or me. 

So again, I have yet to hear a satisfying reason for rewriting the UI and throwing away all our work on it.

**Pull request merged**
